# Generated by Django 5.1.15 on 2026-04-26 13:32

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['site__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('size_label', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='core.parcel')),
            ],
            options={
                'ordering': ['parcel__site__name', 'parcel__code', 'code'],
            },
        ),
        migrations.AddField(
            model_name='parcel',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='core.site'),
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('gate_type', models.CharField(choices=[('primary', 'Glavni ulaz'), ('service', 'Servisni ulaz')], default='primary', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='core.site')),
            ],
            options={
                'ordering': ['site__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AccessRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('width_m', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_roads', to='core.site')),
            ],
            options={
                'ordering': ['site__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ContainerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('status', models.CharField(choices=[('free', 'Slobodan'), ('reserved', 'Rezerviran'), ('occupied', 'Zauzet'), ('blocked', 'Blokiran'), ('maintenance', 'Servis')], default='free', max_length=20)),
                ('area_m2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.container')),
            ],
            options={
                'ordering': ['container__code', 'position'],
                'constraints': [models.UniqueConstraint(fields=('container', 'code'), name='unique_unit_code_per_container'), models.UniqueConstraint(fields=('container', 'position'), name='unique_unit_position_per_container')],
            },
        ),
        migrations.AddConstraint(
            model_name='container',
            constraint=models.UniqueConstraint(fields=('parcel', 'code'), name='unique_container_code_per_parcel'),
        ),
        migrations.AddConstraint(
            model_name='parcel',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='unique_parcel_code_per_site'),
        ),
        migrations.AddConstraint(
            model_name='gate',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='unique_gate_code_per_site'),
        ),
        migrations.AddConstraint(
            model_name='accessroad',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='unique_access_road_code_per_site'),
        ),
    ]
